/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.advent.MainApp;
import org.advent.Utils;


public class App implements MainApp{
    

    public static void main(String[] args) throws Exception {
        Utils.DEBUG = true;
        Utils.main(new App());
    }
    
    
    public void run() throws Exception {
        
        Utils.start("day4", "data0.in", line->{
            Utils.debug(line);
        });
    }
}

